### PR TITLE
Pluggable message class and pep8 fixes

### PR DESCRIPTION
**Pull request by Gr1N**
Hi!

I want to introduce some simple but useful functionality. In some cases we need to redefine message class, e.g. add some additional attributes. In current library this is impossible (yes I know about python.mock, but it is dirty).

Also I fixed some pep8 warning and unused imports.

What do you think?

### CODE REVIEW

**Comment by wallyqs** [comment]
I think sounds good, thanks for the pep8 fixes too! 👍

**Comment by Gr1N** [comment]
Nice!

@wallyqs, could you please create new package (something like v0.3.1) with this functionality and publish on PyPI?

**Comment by wallyqs** [comment]
OK, pushed earlier a minor release with your changes with tag `v0.3.1`, thanks again for the contribution!

**Comment by Gr1N** [comment]
Many thanks!

**Pull request merged**
