### PR TITLE
fixup reconnect: raise `NatsError` on empty server info response

### PR DESCRIPTION
**Pull request by Gr1N**
Hi!

Here is a small fix for reconnect logic. @wallyqs what do you think about fix? Or maybe you know a better solution?

Best regards.

### CODE REVIEW

**Comment by wallyqs** [comment]
Thanks for the patch, this is good for now. Tests coverage would be nice but can take a look at adding before making a release with the fix.

**Comment by Gr1N** [comment]
Could you please upload new version of package?

**Comment by wallyqs** [comment]
Thanks again for the contribution, have uploaded a new version of the package now which includes this fix: https://github.com/nats-io/asyncio-nats/releases/tag/v0.6.2

**Comment by Gr1N** [comment]
Thanks!

**Pull request merged**
