### PR TITLE
Added async callbacks wrapped in functools.partial

### PR DESCRIPTION
**Pull request by aratz-lasa**
Possibility to add async functions wrapped in functools.partial, when creating a subscription.

### CODE REVIEW

**Comment by aratz-lasa** [comment]
Will this pull request be merged? Just curious 🤔

**Comment by wallyqs** [comment]
Hi, thanks for the PR and sorry for the late feedback. I think change LGTM but we need to add a small test for it.  I've added one here https://github.com/nats-io/asyncio-nats/compare/functools-subs let me know if it looks good to you then I'll merge.  Also maybe should include some examples here: https://github.com/nats-io/asyncio-nats/tree/master/examples

**Comment by aratz-lasa** [comment]
I see it very correct! Do you want me to write an example?

**Comment by wallyqs** [comment]
OK! I will merge this then, and yes more examples would be great :) thanks!

**Pull request merged**
